"""remove message content column

Revision ID: c04bedadc34a
Revises: de810ca65d55
Create Date: 2026-02-09 02:39:15.658384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04bedadc34a'
down_revision: Union[str, None] = 'de810ca65d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("UPDATE messages SET content = COALESCE(content_text, '')")
    op.alter_column('messages', 'content', nullable=False)
    # ### end Alembic commands ###
