"""stream_event_log_snapshot

Revision ID: de810ca65d55
Revises: edde253e2822
Create Date: 2026-02-08 04:33:16.902651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'de810ca65d55'
down_revision: Union[str, None] = 'edde253e2822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('message_id', GUID(), nullable=False),
    sa.Column('chat_id', GUID(), nullable=False),
    sa.Column('stream_id', GUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('render_payload', sa.JSON(), nullable=False),
    sa.Column('audit_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_events_chat_id_created_at', 'message_events', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_message_events_chat_id_stream_id_seq', 'message_events', ['chat_id', 'stream_id', 'seq'], unique=False)
    op.create_index('idx_message_events_message_id_seq', 'message_events', ['message_id', 'seq'], unique=False)
    op.create_index('uq_message_events_stream_seq', 'message_events', ['stream_id', 'seq'], unique=True)
    op.add_column('chats', sa.Column('last_event_seq', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('messages', sa.Column('content_text', sa.Text(), server_default='', nullable=False))
    op.add_column('messages', sa.Column('content_render', sa.JSON(), server_default='{"segments": []}', nullable=False))
    op.add_column('messages', sa.Column('last_seq', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('messages', sa.Column('active_stream_id', GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'active_stream_id')
    op.drop_column('messages', 'last_seq')
    op.drop_column('messages', 'content_render')
    op.drop_column('messages', 'content_text')
    op.drop_column('chats', 'last_event_seq')
    op.drop_index('uq_message_events_stream_seq', table_name='message_events')
    op.drop_index('idx_message_events_message_id_seq', table_name='message_events')
    op.drop_index('idx_message_events_chat_id_stream_id_seq', table_name='message_events')
    op.drop_index('idx_message_events_chat_id_created_at', table_name='message_events')
    op.drop_table('message_events')
    # ### end Alembic commands ###
